[package]
name = "metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { workspace = true }
nom_locate = { workspace = true }
encoding_rs = { workspace = true }
indexmap = { workspace = true }
